# Generated by Django 2.2.1 on 2019-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('professional_class', models.CharField(max_length=32, null=True, verbose_name='专业班级')),
                ('student_id', models.CharField(max_length=32, verbose_name='学号或者账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('phone', models.IntegerField(null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'Stu',
            },
        ),
    ]
